spring:
  config:
    activate:
      on-profile: docs

springdoc:
  swagger-ui:
    persist-authorization: true
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
    classification:
      readyToUseGroupName: 개발 완료 API
      workInProgressGroupName: 개발 진행중 API
      deprecatedGroupName: 더이상 유지보수되지 않는 API

---
spring:
  config:
    activate:
      on-profile: prod

springdoc:
  swagger-ui:
    enabled: false
