spring:
  config:
    activate:
      on-profile: "db-default"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:${DB_PORT}/${DB_SCHEMA}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 100

  flyway:
    enabled: true
    encoding: UTF-8
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration

decorator:
  datasource:
    p6spy:
      enable-logging: true   # 원본 default 프로필에서 ON

---

spring:
  config:
    activate:
      on-profile: db-prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:${DB_PORT}/${DB_SCHEMA}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 100

  flyway:
    enabled: true
    encoding: UTF-8
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration

decorator:
  datasource:
    p6spy:
      enable-logging: false  # 원본 prod에서 OFF

